/**
 * Deterministic PLAN for the synthetic development dataset.
 *
 * Pure functions only: no database, no filesystem, no clock, no randomness
 * beyond the seeded RNG. The same seed always yields the same dataset
 * description, which is what makes the seeder reproducible and unit-testable
 * (see test/synthetic-seed.e2e-spec.ts). The runner
 * (scripts/synthetic-seed.ts) is what turns this description into rows through
 * the real services.
 *
 * Vacancies are referenced by INDEX, never by publicSlug: slugs carry a random
 * suffix generated by the vacancy service at creation time, so only the runner
 * knows them.
 */
import {
  DEPARTMENTS,
  EMPLOYMENT_TYPES,
  EXPERIENCE_LEVELS,
  Rng,
  TRACKS,
  TRACK_BY_KEY,
  makePerson,
  orgSpecs,
  pickResumeLocale,
  resumeLines,
  spokenLanguages,
  vacancyDescription,
  type CandidateContent,
  type Region,
  type ResumeLocale,
  type Track,
} from './synthetic-seed.data';

/** Fixed seed: bump only when the dataset is meant to change. */
export const SYNTHETIC_SEED = 20260821;

/** Single dev password for every synthetic account (development only). */
export const SYNTHETIC_PASSWORD = 'DevPassword123!';

/**
 * Marker that makes reset surgical. A synthetic user is `<role><NNN>@example.test`
 * — never a hand-made dev account: `jasur.toshmatov@example.test` and
 * `candidate-auth-test@example.test` deliberately do NOT match, because the
 * local part must be exactly a role word followed by digits.
 */
export const SYNTHETIC_EMAIL_PATTERN =
  /^(candidate|owner|recruiter)\d{3}@example\.test$/;

/** Organizations created by this seeder all carry this slug prefix. */
export const SYNTHETIC_ORG_SLUG_PREFIX = 'syn-';

export const isSyntheticEmail = (email: string): boolean =>
  SYNTHETIC_EMAIL_PATTERN.test(email);

const pad = (n: number): string => String(n).padStart(3, '0');

export type MemberRole = 'OWNER' | 'HR_ADMIN' | 'RECRUITER' | 'INTERVIEWER';
export type PlannedStatus = 'DRAFT' | 'OPEN' | 'CLOSED' | 'ARCHIVED';
export type PlannedRequirementType =
  | 'SKILL'
  | 'EXPERIENCE'
  | 'EDUCATION'
  | 'LANGUAGE'
  | 'OTHER';

export interface PlannedOrg {
  name: string;
  slug: string;
  city: string;
  focus: string[];
}

export interface PlannedOrgUser {
  email: string;
  fullName: string;
  memberships: { orgIndex: number; role: MemberRole }[];
}

export interface PlannedExperience {
  title: string;
  company: string;
  startDate: string;
  endDate?: string;
  description: string;
}

export interface PlannedCandidate {
  email: string;
  fullName: string;
  region: Region;
  resumeLocale: ResumeLocale;
  trackKey: string;
  headline: string;
  location: string;
  phone: string;
  summary: string;
  skills: string[];
  languages: string[];
  years: number;
  experience: PlannedExperience[];
  education: { institution: string; degree: string; field: string; startYear: number; endYear: number }[];
  /** Most candidates have one; a minority deliberately do not. */
  hasResume: boolean;
  resumeFileName: string;
  resumeLines: string[];
}

export interface PlannedRequirement {
  text: string;
  type: PlannedRequirementType;
  required: boolean;
}

export interface PlannedVacancy {
  orgIndex: number;
  trackKey: string;
  title: string;
  department: string;
  location: string;
  employmentType: string;
  experienceLevel: string;
  description: string;
  status: PlannedStatus;
  requirements: PlannedRequirement[];
}

export interface SyntheticPlan {
  seed: number;
  orgs: PlannedOrg[];
  orgUsers: PlannedOrgUser[];
  candidates: PlannedCandidate[];
  vacancies: PlannedVacancy[];
  /** Candidate → vacancy, deduped; only OPEN vacancies and candidates with a resume. */
  applications: { candidateIndex: number; vacancyIndex: number }[];
  /** Candidate → vacancy bookmarks; only OPEN vacancies (the real service refuses others). */
  savedJobs: { candidateIndex: number; vacancyIndex: number }[];
  /** Saved vacancies to CLOSE afterwards, so "saved but now closed" exists. */
  closeAfterSave: number[];
  powerApplicantEmail: string;
}

/**
 * Track/region combinations forced onto the first candidates so the documented
 * demo searches always have strong, findable matches:
 *   "Korean speaking backend engineer"                     → ko + backend
 *   "Docker va Kubernetes biladigan DevOps hodim kerak"    → uz + devops
 *   "React va TypeScript … frontend developer"             → frontend
 *   "backend engineer with NestJS and PostgreSQL"          → backend (en body)
 * `fullCore: true` guarantees every core skill of the track is present.
 */
const GUARANTEED: {
  region: Region;
  trackKey: string;
  resumeLocale: ResumeLocale;
}[] = [
  ...Array.from({ length: 3 }, () => ({ region: 'ko' as Region, trackKey: 'backend', resumeLocale: 'en' as ResumeLocale })),
  ...Array.from({ length: 3 }, () => ({ region: 'ko' as Region, trackKey: 'backend', resumeLocale: 'ko' as ResumeLocale })),
  ...Array.from({ length: 4 }, () => ({ region: 'uz' as Region, trackKey: 'devops', resumeLocale: 'uz' as ResumeLocale })),
  ...Array.from({ length: 2 }, () => ({ region: 'uz' as Region, trackKey: 'devops', resumeLocale: 'en' as ResumeLocale })),
  ...Array.from({ length: 4 }, () => ({ region: 'west' as Region, trackKey: 'frontend', resumeLocale: 'en' as ResumeLocale })),
  ...Array.from({ length: 2 }, () => ({ region: 'ru' as Region, trackKey: 'frontend', resumeLocale: 'ru' as ResumeLocale })),
  ...Array.from({ length: 4 }, () => ({ region: 'uz' as Region, trackKey: 'backend', resumeLocale: 'en' as ResumeLocale })),
  ...Array.from({ length: 2 }, () => ({ region: 'west' as Region, trackKey: 'backend', resumeLocale: 'en' as ResumeLocale })),
];

export const CANDIDATE_COUNT = 140;

const EMPLOYERS_FOR_PROFILE = [
  'Silk Route Systems', 'Registon Soft', 'Hanbit Digital', 'Severnaya Data',
  'Oqtepa Commerce', 'Blue Poplar Media', 'Deltafin Labs', 'Yulduz Telecom',
];

const PROFILE_UNIVERSITIES = [
  'Tashkent University of Information Technologies',
  'Inha University in Tashkent',
  'Seoul National University',
  'University of Warsaw',
  'TU Berlin',
  'Al-Farabi Kazakh National University',
];

/** Skill set for one candidate. `fullCore` keeps demo searches reliable. */
function candidateSkills(rng: Rng, track: Track, fullCore: boolean): string[] {
  const skills = fullCore
    ? [...track.core]
    : track.core.filter(() => rng.chance(0.85));
  if (skills.length === 0) skills.push(track.core[0]!);
  skills.push(...rng.pickN(track.extra, rng.int(2, 4)));
  if (rng.chance(0.15)) skills.push(rng.pick(track.rare));
  return skills;
}

function seniorityTitle(rng: Rng, track: Track, years: number): string {
  const base = rng.pick(track.titles);
  if (years >= 8) return `Senior ${base}`;
  if (years <= 2) return `Junior ${base}`;
  return base;
}

function planCandidate(rng: Rng, index: number): PlannedCandidate {
  const forced = GUARANTEED[index];
  const person = makePerson(rng);
  const region = forced?.region ?? person.region;
  const trackKey = forced?.trackKey ?? rng.pick(TRACKS).key;
  const track = TRACK_BY_KEY.get(trackKey)!;
  const resumeLocale = forced?.resumeLocale ?? pickResumeLocale(rng, region);

  const email = `candidate${pad(index + 1)}@example.test`;
  const years = rng.weighted<number>([
    [rng.int(1, 2), 0.2],
    [rng.int(3, 5), 0.4],
    [rng.int(6, 9), 0.3],
    [rng.int(10, 14), 0.1],
  ]);
  const skills = candidateSkills(rng, track, forced !== undefined);
  const languages = spokenLanguages(rng, region);
  const headline = seniorityTitle(rng, track, years);

  const content: CandidateContent = {
    fullName: person.fullName,
    headlineTitle: headline,
    track,
    skills,
    years,
    location: person.location,
    languages,
    resumeLocale,
    email,
  };

  const employerA = rng.pick(EMPLOYERS_FOR_PROFILE);
  const startYearA = 2026 - Math.min(years, rng.int(1, 4));
  const gradYear = 2026 - years - rng.int(0, 3);

  return {
    email,
    fullName: person.fullName,
    region,
    resumeLocale,
    trackKey,
    headline,
    location: person.location,
    phone: `+998 90 ${pad(index + 100)} ${pad(rng.int(1, 999))}`,
    summary:
      `${track.label} engineer with ${years} years of experience. ` +
      `Core stack: ${skills.slice(0, 4).join(', ')}.`,
    skills,
    languages,
    years,
    experience: [
      {
        title: headline,
        company: employerA,
        startDate: `${startYearA}-03`,
        description: `Built and operated ${skills.slice(0, 2).join(' and ')} services in production.`,
      },
      {
        title: track.titles[0]!,
        company: rng.pick(EMPLOYERS_FOR_PROFILE),
        startDate: `${gradYear + 1}-09`,
        endDate: `${startYearA}-02`,
        description: `Worked across ${skills.slice(1, 3).join(', ')} on a small product team.`,
      },
    ].slice(0, years >= 3 ? 2 : 1),
    education: [
      {
        institution: rng.pick(PROFILE_UNIVERSITIES),
        degree: 'BSc',
        field: 'Computer Science',
        startYear: gradYear - 4,
        endYear: gradYear,
      },
    ],
    // Most candidates carry a resume; a deliberate minority does not, so the
    // "apply without resume" and empty-match paths stay exercisable.
    hasResume: rng.chance(0.92),
    resumeFileName: `${person.fullName.toLowerCase().replace(/[^a-z]+/g, '-')}-resume.docx`,
    resumeLines: resumeLines(rng, content),
  };
}

/** Requirements engineered so evidence coverage lands on all three labels. */
function planRequirements(rng: Rng, track: Track): PlannedRequirement[] {
  const requirements: PlannedRequirement[] = [];

  for (const skill of rng.pickN(track.core, rng.int(2, 3))) {
    requirements.push({ text: skill, type: 'SKILL', required: true });
  }
  for (const skill of rng.pickN(track.extra, rng.int(1, 2))) {
    requirements.push({ text: skill, type: 'SKILL', required: rng.chance(0.35) });
  }
  // A rare skill nobody in the pool reliably has: the main source of
  // unsupported requirements, hence PARTIAL and WEAK coverage.
  if (rng.chance(0.35)) {
    requirements.push({ text: rng.pick(track.rare), type: 'SKILL', required: true });
  }
  requirements.push({
    text: `${rng.int(2, 6)}+ years of professional experience as a ${track.label} engineer`,
    type: 'EXPERIENCE',
    required: true,
  });
  if (rng.chance(0.4)) {
    requirements.push({
      text: rng.pick([
        'Professional working English',
        'Korean language for daily team communication',
        'Russian or Uzbek for local stakeholder communication',
      ]),
      type: 'LANGUAGE',
      required: rng.chance(0.5),
    });
  }
  if (rng.chance(0.3)) {
    requirements.push({
      text: 'BSc in Computer Science or equivalent practical experience',
      type: 'EDUCATION',
      required: false,
    });
  }
  return requirements;
}

function planVacancy(rng: Rng, org: PlannedOrg, orgIndex: number): PlannedVacancy {
  const trackKey = rng.chance(0.85)
    ? rng.pick(org.focus)
    : rng.pick(TRACKS).key;
  const track = TRACK_BY_KEY.get(trackKey)!;
  const title = rng.pick(track.vacancyTitles);
  const requirements = planRequirements(rng, track);

  return {
    orgIndex,
    trackKey,
    title,
    department: DEPARTMENTS[trackKey] ?? 'Engineering',
    location: rng.chance(0.35) ? `${org.city} / Remote` : org.city,
    employmentType: rng.pick(EMPLOYMENT_TYPES),
    experienceLevel: rng.pick(EXPERIENCE_LEVELS),
    description: vacancyDescription(
      rng,
      org.name,
      title,
      requirements.filter((r) => r.type === 'SKILL').map((r) => r.text),
    ),
    // Mostly OPEN: only OPEN vacancies are candidate-visible and indexed.
    status: rng.weighted<PlannedStatus>([
      ['OPEN', 0.78], ['DRAFT', 0.1], ['CLOSED', 0.09], ['ARCHIVED', 0.03],
    ]),
    requirements,
  };
}

/**
 * Builds the whole dataset description.
 *
 * @param applicationScale multiplies the per-candidate application counts
 *   (not the power applicant). Lets a machine-constrained run stay smaller
 *   without changing anything else about the dataset.
 */
export function buildPlan(
  seed = SYNTHETIC_SEED,
  { applicationScale = 1, powerApplicantTarget = 110 } = {},
): SyntheticPlan {
  const rng = new Rng(seed);
  const orgs = orgSpecs();

  // --- Organization accounts: one OWNER each, plus a few teammates ---------
  const orgUsers: PlannedOrgUser[] = [];
  orgs.forEach((org, orgIndex) => {
    orgUsers.push({
      email: `owner${pad(orgIndex + 1)}@example.test`,
      fullName: makePerson(rng).fullName,
      memberships: [{ orgIndex, role: 'OWNER' }],
    });
  });

  let recruiterNo = 0;
  orgs.forEach((_, orgIndex) => {
    // Keeps ORGANIZATION accounts (36 owners + teammates) inside the target
    // 50–70 band while still giving most organizations a real team.
    const teammates = rng.weighted<number>([[0, 0.48], [1, 0.4], [2, 0.12]]);
    for (let i = 0; i < teammates; i++) {
      recruiterNo += 1;
      const memberships: PlannedOrgUser['memberships'] = [
        {
          orgIndex,
          role: rng.weighted<MemberRole>([
            ['RECRUITER', 0.6], ['HR_ADMIN', 0.2], ['INTERVIEWER', 0.2],
          ]),
        },
      ];
      // Multi-organization membership stays legal for ORGANIZATION accounts
      // and must remain represented in the dataset.
      if (rng.chance(0.28)) {
        const other = rng.int(0, orgs.length - 1);
        if (other !== orgIndex) {
          memberships.push({ orgIndex: other, role: 'INTERVIEWER' });
        }
      }
      orgUsers.push({
        email: `recruiter${pad(recruiterNo)}@example.test`,
        fullName: makePerson(rng).fullName,
        memberships,
      });
    }
  });

  // --- Candidate accounts --------------------------------------------------
  const candidates = Array.from({ length: CANDIDATE_COUNT }, (_, index) =>
    planCandidate(rng, index),
  );

  // --- Vacancies -----------------------------------------------------------
  const vacancies: PlannedVacancy[] = [];
  orgs.forEach((org, orgIndex) => {
    const count = rng.int(4, 7);
    for (let i = 0; i < count; i++) {
      vacancies.push(planVacancy(rng, org, orgIndex));
    }
  });

  const openIndexes = vacancies
    .map((vacancy, index) => ({ vacancy, index }))
    .filter(({ vacancy }) => vacancy.status === 'OPEN')
    .map(({ index }) => index);

  // --- Applications --------------------------------------------------------
  // Only candidates with a resume can apply (the real apply path refuses
  // otherwise), and only to OPEN vacancies. One application per vacancy.
  const applications: { candidateIndex: number; vacancyIndex: number }[] = [];
  const appliable = candidates
    .map((candidate, index) => ({ candidate, index }))
    .filter(({ candidate }) => candidate.hasResume);

  const addApplications = (candidateIndex: number, wanted: number) => {
    const chosen = new Set<number>();
    const track = candidates[candidateIndex]!.trackKey;
    // Prefer same-track vacancies (realistic, and produces STRONG coverage),
    // with a minority of off-track applications (which land WEAK).
    const preferred = openIndexes.filter(
      (i) => vacancies[i]!.trackKey === track,
    );
    let guard = 0;
    while (chosen.size < wanted && guard < wanted * 40) {
      guard += 1;
      const pool =
        preferred.length > 0 && rng.chance(0.7) ? preferred : openIndexes;
      chosen.add(rng.pick(pool));
    }
    for (const vacancyIndex of chosen) {
      applications.push({ candidateIndex, vacancyIndex });
    }
  };

  // The power applicant: enough applications for My Applications paging to be
  // exercised for real (the business rule is one per vacancy, so this needs
  // 100+ distinct OPEN vacancies to exist — it does).
  const powerApplicant = appliable[0]!;
  addApplications(
    powerApplicant.index,
    Math.min(powerApplicantTarget, openIndexes.length),
  );
  // A second, milder heavy applicant.
  if (appliable[1]) addApplications(appliable[1].index, Math.round(25 * applicationScale));

  for (const { index } of appliable.slice(2)) {
    const wanted = rng.weighted<number>([
      [0, 0.35],
      [rng.int(1, 2), 0.35],
      [rng.int(3, 5), 0.22],
      [rng.int(6, 12), 0.08],
    ]);
    const scaled = Math.round(wanted * applicationScale);
    if (scaled > 0) addApplications(index, scaled);
  }

  // --- Saved jobs ----------------------------------------------------------
  const savedJobs: { candidateIndex: number; vacancyIndex: number }[] = [];
  candidates.forEach((_, candidateIndex) => {
    const wanted = rng.weighted<number>([
      [0, 0.25], [rng.int(1, 2), 0.4], [rng.int(3, 6), 0.35],
    ]);
    const chosen = new Set<number>();
    let guard = 0;
    while (chosen.size < wanted && guard < wanted * 20) {
      guard += 1;
      chosen.add(rng.pick(openIndexes));
    }
    for (const vacancyIndex of chosen) {
      savedJobs.push({ candidateIndex, vacancyIndex });
    }
  });

  // Close a handful of SAVED vacancies afterwards: the saved-jobs list must
  // show a job that is no longer open.
  const savedOnce = [...new Set(savedJobs.map((s) => s.vacancyIndex))];
  const closeAfterSave = rng
    .pickN(savedOnce, Math.min(12, savedOnce.length))
    .sort((a, b) => a - b);

  return {
    seed,
    orgs,
    orgUsers,
    candidates,
    vacancies,
    applications,
    savedJobs,
    closeAfterSave,
    powerApplicantEmail: powerApplicant.candidate.email,
  };
}

/** Headline counts, for the report and for tests. */
export function planSummary(plan: SyntheticPlan) {
  const openVacancies = plan.vacancies.filter((v) => v.status === 'OPEN').length;
  const perCandidate = new Map<number, number>();
  for (const app of plan.applications) {
    perCandidate.set(app.candidateIndex, (perCandidate.get(app.candidateIndex) ?? 0) + 1);
  }
  return {
    organizations: plan.orgs.length,
    organizationUsers: plan.orgUsers.length,
    candidates: plan.candidates.length,
    totalUsers: plan.orgUsers.length + plan.candidates.length,
    resumes: plan.candidates.filter((c) => c.hasResume).length,
    vacancies: plan.vacancies.length,
    openVacancies,
    requirements: plan.vacancies.reduce((n, v) => n + v.requirements.length, 0),
    applications: plan.applications.length,
    maxApplicationsPerCandidate: Math.max(0, ...perCandidate.values()),
    savedJobs: plan.savedJobs.length,
    closedAfterSave: plan.closeAfterSave.length,
    multiOrgUsers: plan.orgUsers.filter((u) => u.memberships.length > 1).length,
  };
}
